version: '3'
services:
  backend:
    build: .
    ports:
      - '3000:3000'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_URI=mongodb://mongo:27017/gravedust
    depends_on:
      - mongo
    networks:
      - grave-dust-network

  frontend:
    build:
      context: ./frontend
    ports:
      - '3001:3000'
    depends_on:
      - backend
    networks:
      - grave-dust-network

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'  # Expose MongoDB port for external access
    volumes:
      - mongo-data:/data/db
    networks:
      - grave-dust-network

volumes:
  mongo-data:

networks:
  grave-dust-network:
    external: true
