version: '3'
services:
  backend:
    build: .
    ports:
      - '${BACKEND_SERVER_PORT}:${BACKEND_SERVER_PORT}'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MONGO_URI=${MONGO_URI}
      - PORT=${BACKEND_SERVER_PORT} # Adding this to ensure the backend knows which port to use
    depends_on:
      - mongo
    networks:
      - grave-dust-network

  frontend:
    build:
      context: ./frontend
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    environment:
      - PORT=${FRONTEND_PORT} # Ensure frontend uses the correct port
    depends_on:
      - backend
    networks:
      - grave-dust-network

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'  # Expose MongoDB port for external access
    volumes:
      - mongo-data:/data/db
    networks:
      - grave-dust-network

volumes:
  mongo-data:

networks:
  grave-dust-network:
    external: true
